name: Deploy React App to GCP

on:
  push:
    branches:
      - main  # Trigger deployment on pushes to this branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4


    - name: Install Dependencies
      run: |
        npm install

    - name: Build React App
      run: |
        npm run build  # Dynamically generates the "dist" folder during the pipeline execution
   
    - name: Debug SSH
      run: |
        echo "IP Address: ${{ secrets.GCP_IP }}"
        ssh-keyscan -H ${{ secrets.GCP_IP }}

    - name: Set Up SSH
      run: |
        # Configure SSH using the private key stored in GitHub Secrets
        mkdir -p ~/.ssh
        echo "${{ secrets.GCP_SSH_FILE }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        ssh-keyscan -H ${{ secrets.GCP_IP }} >> ~/.ssh/known_hosts
    
    - name: Deploy Built Files to GCP VM
      run: |
        # Ensure correct permissions on the target directory
        ssh ${{ secrets.GCP_USER }}@${{ secrets.GCP_IP }} "sudo chown -R ${{ secrets.GCP_USER }}:www-data /var/www/html && sudo chmod -R 755 /var/www/html"
        
        # Upload the dynamically built files to the GCP server
        scp -r dist/* ${{ secrets.GCP_USER }}@${{ secrets.GCP_IP }}:/var/www/html/


    - name: Verify Deployment
      run: |
        ssh ${{ secrets.GCP_USER }}@${{ secrets.GCP_IP }} "ls -la /var/www/html/"

