name: Build and Print Env

on:
  push:
    branches:
      - main  # Trigger on push to the main branch

jobs:
  build-and-check:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Install Dependencies
        run: npm install

      - name: Verify Secret Exists
        run: |
          if [[ -z "${{ secrets.VITE_PUBLIC_API_URL_DEV }}" ]]; then
            echo "❌ Secret is NOT available! Check GitHub settings."
            exit 1
          else
            echo "✅ Secret is available!"
          fi

      - name: Set API URL
        run: |
          echo "VITE_PUBLIC_API_URL=${{ secrets.VITE_PUBLIC_API_URL_DEV }}" >> $GITHUB_ENV

      - name: Debug - Print API URL Safely
        run: |
          echo "VITE_PUBLIC_API_URL: $(echo $VITE_PUBLIC_API_URL | sed 's/./& /g')"

      - name: Build React App
        run: |
          npm run build
        env:
          VITE_PUBLIC_API_URL: ${{ env.VITE_PUBLIC_API_URL }}
