name: Build and Print Env

on:
  push:
    branches:
      - main  # Trigger on push to the main branch

jobs:
  build-and-check:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'

    steps:
      # Step 1: Checkout Code
      - name: Checkout Code
        uses: actions/checkout@v4
      
      # Step 2: Install Dependencies
      - name: Install Dependencies
        run: |
          npm install
      
      # Step 3: Set API URL Based on GitHub Variable
      - name: Set API URL
        run: |
          echo "VITE_PUBLIC_API_URL=${{ vars.VITE_PUBLIC_API_URL_DEV }}" >> $GITHUB_ENV
      
      # Step 4: Print API URL (Should now correctly show the value)
      - name: Print API URL
        run: |
          echo "VITE_PUBLIC_API_URL is set to: $VITE_PUBLIC_API_URL"

      # Step 5: Build the React App with Correct API URL
      - name: Build React App
        run: |
          npm run build
        env:
          VITE_PUBLIC_API_URL: ${{ env.VITE_PUBLIC_API_URL }}
